spring:
  datasource:
    url: jdbc:h2:mem:testdb
    h2:
      console:
        enabled: true

    jpa:
      generate-ddl: true

      hibernate:
        ddl-auto: update
        # create-drop for reset

      show-sql: false

      defer-datasource-initialization: true